name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  my-job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun index.ts
      - run: bun run build
